service: sls-app-sync
frameworkVersion: '2'
variablesResolutionMode: 20210326

plugins:
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverless
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'appsync:GraphQL'
      Resource: arn:aws:appsync:*
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'arn:aws:dynamodb:${self:provider.region}:*:*'

functions:
  MenteeAppSyncHandler:
    handler: src/appsync/lib/mentee-handler.graphql
    environment:
      DB_DATABASE: ${self:custom.rdsInstance.DB_DATABASE}
      DB_HOST: ${self:custom.rdsInstance.DB_HOST}
      DB_PASSWORD: ${self:custom.rdsInstance.DB_PASSWORD}
      DB_PORT: ${self:custom.rdsInstance.DB_PORT}
      DB_USERNAME: ${self:custom.rdsInstance.DB_USERNAME}

  MentorAppSyncHandler:
    handler: src/appsync/lib/mentor-handler.graphql

  AdminAppSyncHandler:
    handler: src/appsync/lib/admin-handler.graphql

custom:
  accountId: #{AWS::AccountId}
  rdsInstance: ${file(env.yml):${self:provider.stage}, file(env.yml):dev}
  appSync:
    - name: mentee-api-${self:provider.stage}
      authenticationType: API_KEY
      serviceRole: 'AppSyncServiceRole'
      mappingTemplatesLocation: './src/appsync'
      mappingTemplates:
        - dataSource: awsLambdaDataSource
          type: Query #Query, Mutation, Subscription
          field: getProgram
          request: 'mapping-templates/getProgram-request-mapping-template.txt'
          response: 'mapping-templates/getProgram-response-mapping-template.txt'
      schema: './src/appsync/db/mentee/schema.graphql'
      dataSources:
        - type: AWS_LAMBDA
          name: awsLambdaDataSource
          description: 'Lambda DataSource'
          config:
            lambdaFunctionArn: { Fn::GetAtt: [MenteeAppSyncHandlerLambdaFunction, Arn] }
            serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }

    - name: mentor-api-${self:provider.stage}
      authenticationType: API_KEY
      serviceRole: 'AppSyncServiceRole'
      mappingTemplatesLocation: './src/appsync'
      mappingTemplates:
        - dataSource: awsLambdaDataSource
          type: Query #Query, Mutation, Subscription
          field: getProgram
          request: 'mapping-templates/getProgram-request-mapping-template.txt'
          response: 'mapping-templates/getProgram-response-mapping-template.txt'
      schema: './src/appsync/db/mentor/schema.graphql'
      dataSources:
        - type: AWS_LAMBDA
          name: awsLambdaDataSource
          description: 'Lambda DataSource'
          config:
            lambdaFunctionArn: { Fn::GetAtt: [MentorAppSyncHandlerLambdaFunction, Arn] }
            serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }

    - name: admin-api-${self:provider.stage}
      authenticationType: API_KEY
      serviceRole: 'AppSyncServiceRole'
      mappingTemplatesLocation: './src/appsync'
      mappingTemplates:
        - type: Query #Query, Mutation, Subscription
          dataSource: awsLambdaDataSource
          field: getProgram
          request: 'mapping-templates/getProgram-request-mapping-template.txt'
          response: 'mapping-templates/getProgram-response-mapping-template.txt'

        - type: Query #Query, Mutation, Subscription
          dataSource: awsLambdaDataSource
          field: listPrograms
          request: 'mapping-templates/listPrograms-request-mapping-template.txt'
          response: 'mapping-templates/listPrograms-response-mapping-template.txt'

        - type: Mutation #Query, Mutation, Subscription
          dataSource: awsLambdaDataSource
          field: createProgram
          request: 'mapping-templates/createProgram-request-mapping-template.txt'
          response: 'mapping-templates/createProgram-response-mapping-template.txt'
      schema: './src/appsync/db/admin/schema.graphql'
      dataSources:
        - type: AWS_LAMBDA
          name: awsLambdaDataSource
          description: 'Lambda DataSource'
          config:
            lambdaFunctionArn: { Fn::GetAtt: [AdminAppSyncHandlerLambdaFunction, Arn] }
            serviceRoleArn: { Fn::GetAtt: [AppSyncLambdaServiceRole, Arn] }

resources:
  Resources:
    # AppSync lambda role
    AppSyncLambdaServiceRole:
      Type: 'AWS::IAM::Role'
      Properties:
        RoleName: 'Lambda-${self:custom.appSync.0.serviceRole}'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal:
                Service:
                  - 'appsync.amazonaws.com'
              Action:
                - 'sts:AssumeRole'
        Policies:
          - PolicyName: 'Lambda-${self:custom.appSync.0.serviceRole}-Policy'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 'lambda:invokeFunction'
                  Resource:
                    - 'arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-MentorAppSyncHandler'
                    - 'arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-MentorAppSyncHandler:*'
                    - 'arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-MenteeAppSyncHandler'
                    - 'arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-MenteeAppSyncHandler:*'
                    - 'arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-AdminAppSyncHandler'
                    - 'arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service}-${self:provider.stage}-AdminAppSyncHandler:*'
