name: MENV2 Deploy Dev
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  deploy-dev:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Serverless Framework
        run: cd API && npm install -g serverless

      - name: Setup Environment
        run: |
          cat > env.yml << EOF
          ${{ secrets.DEV_ENV }}
          EOF

      - name: Install Dependencies
        run: cd API && npm install

      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: cd API && deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
