name: MENV2 Deploy Dev
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  deploy-dev:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Serverless Framework
        run: cd API && npm install -g serverless

      - name: Setup Environment
        run: |
          cat > API/env.yml << EOF
          ${{ secrets.ENV }}
          EOF

      - name: Install Dependencies
        run: cd API && npm install

      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Lambda functions
        run: cd API && sls deploy -s dev
