name: MENV2 Deploy Dev
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  setup-workspace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Serverless Framework
        run: npm install -g serverless

  deploy-dev:
      name: deploy
      runs-on: ubuntu-latest
      needs: setup-workspace
      steps:
        - name: Create Environment
          run: cd mentorship-service && \
          |
            cat > env.yml << EOF
            ${{ secrets.DEV_ENV }}
            EOF

        - name: Install Dependencies
          run: cd mentorship-service && npm install

        - name: Authenticate Serverless
          run: cd mentorship-service && sls config credentials --provider aws --key ${{ secrets.DEV_AWS_ACCESS_KEY_ID }} --secret ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

        - name: Deploy Lambda functions
          run: cd mentorship-service && sls deploy -s dev
