# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

    
on:
  workflow_dispatch

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
        
    # Deployment of your project
    - name: serverless deploy
      uses: suprgames/serverless-github-action@v1.77
      with:
        args: deploy --stage dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
